services:
  master:
    image: postgres:16.2-alpine3.19
    container_name: primary_db
    volumes:
      - primary-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: primary_db
    restart: unless-stopped
    ports:
      - "5400:5432"
  replica1:
    image: postgres:16.2-alpine3.19
    container_name: replica_db
    volumes:
      - replica-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: replica_db
    restart: unless-stopped
    ports:
      - "5401:5432"
volumes:
  primary-db-data:
    name: primary-db-data
  replica-db-data:
    name: replica-db-data
